# Generated by Django 5.2.11 on 2026-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gruppa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Группа'),
        ),
    ]
