# Generated by Django 5.2.11 on 2026-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gruppa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Личный номер студента'),
        ),
    ]
