# Generated by Django 5.2.11 on 2026-03-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_college', '0002_remove_status_user_student_status_slug'),
        ('users', '0003_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network_college.status'),
        ),
    ]
