# Generated by Django 4.2.17 on 2026-04-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupTeacher',
        ),
    ]
