# Generated by Django 5.2.11 on 2026-03-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status_user',
        ),
    ]
