# Generated by Django 5.2.11 on 2026-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_status_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Личный номер'),
        ),
    ]
