# Generated by Django 4.2.17 on 2026-04-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_group_customuser_group_as_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gruppa',
        ),
    ]
