# Generated by Django 5.2.11 on 2026-03-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user_student',
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
