# Generated by Django 5.2.11 on 2026-03-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_college', '0002_remove_status_user_student_status_slug'),
        ('users', '0006_remove_customuser_status_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
