# Generated by Django 5.2.11 on 2026-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('first_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('verification_number', models.CharField(max_length=150, verbose_name='Верификационный номер')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
