# Generated by Django 5.2.11 on 2026-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('invite_code', models.CharField(blank=True, help_text='Уникальный код для регистрации', max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Код активен и может быть использован', null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Время, когда код был использован', null=True)),
            ],
        ),
    ]
