# Generated by Django 4.2.17 on 2026-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_college', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='verification_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Уникальный код для регистрации', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Код активен и может быть использован', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Время, когда код был использован', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
