# Generated by Django 4.2.17 on 2026-04-02 08:40

import admin_college.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='verification_number',
            field=models.CharField(default=admin_college.models.veri, max_length=150, verbose_name='Верификационный номер'),
        ),
    ]
