# Generated by Django 5.2.11 on 2026-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='verification_number',
            field=models.CharField(default=None, max_length=150, verbose_name='Верификационный номер'),
        ),
    ]
