<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-03-31 09:28

=======
# Generated by Django 4.2.17 on 2026-04-02 08:40

import admin_college.models
>>>>>>> 5beab3b4113bbd8b48c959ef633341c8fbe0187b
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='verification_number',
<<<<<<< HEAD
            field=models.CharField(default=None, max_length=150, verbose_name='Верификационный номер'),
=======
            field=models.CharField(default=admin_college.models.veri, max_length=150, verbose_name='Верификационный номер'),
>>>>>>> 5beab3b4113bbd8b48c959ef633341c8fbe0187b
        ),
    ]
