# Generated by Django 5.2.11 on 2026-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_college', '0002_alter_teacher_verification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='verification_number',
            field=models.CharField(max_length=150, verbose_name='Верификационный номер'),
        ),
    ]
